### ISSUE TITLE
Migrate common utils from existing frontend repos to common

### ISSUE THREAD

**Issue by eddieyu1998** [glimpse-protocol/common#2]
# Description

If there are util functions in any individual frontend repo that could be useful to all repos, we should move them into this common repo.

# Acceptance Criteria

All shareable utils are moved to this common repo

# Todo

- [ ] identify shareable util functions in each individual repo
  - [ ] beacon.js
  - [ ] connect.js
  - [ ] universal-creative.js
  - [ ] frontend-ui
  - [ ] frontend-demo
- [ ] move the util functions to this common repo
  - [ ] beacon.js
  - [ ] connect.js
  - [ ] universal-creative.js
  - [ ] frontend-ui
  - [ ] frontend-demo
- [ ] remove any duplication, unify all of the util functions to make them consistent

**Comment by eddieyu1998** [comment]
moving to backlog
